### ISSUE TITLE
[Feature]: Publish Helm chart for Kubernetes deployment

### ISSUE THREAD

**Issue by crivetimihai** [IBM/mcp-context-forge#24]
### 🧭 Type of Feature

- [x] New feature or capability  
- [x] Packaging, automation and deployment  
- [ ] Enhancement to existing functionality  
- [ ] New MCP-compliant server  
- [ ] New component or integration  
- [ ] Developer tooling or test improvement  
- [ ] Other (please describe below)

---

### 🧭 Epic

**Title:** Helm chart for deploying MCP Gateway to Kubernetes  
**Goal:** Provide a versioned, configurable Helm chart for deploying `mcpgateway` to Kubernetes clusters using best practices  
**Why now:** Kubernetes is the standard for cloud-native infrastructure. Offering Helm support will make it easy to integrate MCP Gateway into GitOps workflows, staging environments, and production deployments with observability, secret injection, and scaling.

---

### 🙋‍♂️ User Story 1

**As a:** DevOps engineer  
**I want:** to install MCP Gateway via `helm install`  
**So that:** I can deploy, update, and configure it declaratively in K8s clusters

#### ✅ Acceptance Criteria
```gherkin
Scenario: Install the Helm chart with defaults
  Given I clone the MCP Gateway repo
  When I run helm install mcpgw ./charts/mcpgateway
  Then I should see a Pod, Service, and optional Ingress created
````

---

### 🙋‍♂️ User Story 2

**As a:** developer or tester
**I want:** to override key environment variables via `values.yaml`
**So that:** I can test different databases, ports, secrets, and transports

#### ✅ Acceptance Criteria

```gherkin
Scenario: Set custom environment values
  Given I provide a custom values.yaml with auth and database settings
  When I install the chart
  Then those values should be injected into the container and visible in logs
```

---

### 📐 Design Sketch (Helm structure)

```bash
charts/
└── mcpgateway/
    ├── Chart.yaml
    ├── values.yaml
    └── templates/
        ├── deployment.yaml
        ├── service.yaml
        ├── ingress.yaml
        └── configmap.yaml
```

---

### 🧪 Testing Instructions

**Manual install:**

```bash
helm install mcpgw ./charts/mcpgateway --values values.override.yaml
kubectl get all
```

**Test basic connectivity:**

```bash
kubectl port-forward svc/mcpgw 4444:80 &
export MCPGATEWAY_BEARER_TOKEN=$(python -m mcpgateway.utils.create_jwt_token -u admin)
curl -H "Authorization: Bearer $MCPGATEWAY_BEARER_TOKEN" http://localhost:4444/tools
```

**Test ingress (if enabled):**

```bash
kubectl apply -f test-ingress.yaml
curl -H "Authorization: Bearer $TOKEN" https://gateway.example.com/tools
```

---

### 🔧 `values.override.yaml` Example

This example maps directly to the `.env.example` settings:

```yaml
image:
  repository: ghcr.io/ibm/mcp-context-forge
  tag: latest
  pullPolicy: IfNotPresent

env:
  APP_NAME: MCP_Gateway
  HOST: 0.0.0.0
  PORT: 4444
  DATABASE_URL: sqlite:///./mcp.db
  APP_ROOT_PATH: ""
  CACHE_TYPE: database
  REDIS_URL: redis://redis:6379/0
  CACHE_PREFIX: mcpgw:
  SESSION_TTL: 3600
  MESSAGE_TTL: 600
  BASIC_AUTH_USER: admin
  BASIC_AUTH_PASSWORD: changeme
  AUTH_REQUIRED: true
  JWT_SECRET_KEY: my-test-key
  JWT_ALGORITHM: HS256
  TOKEN_EXPIRY: 10080
  AUTH_ENCRYPTION_SECRET: my-test-salt
  MCPGATEWAY_UI_ENABLED: true
  MCPGATEWAY_ADMIN_API_ENABLED: true
  CORS_ENABLED: true
  ALLOWED_ORIGINS: '["http://localhost:3000"]'
  LOG_LEVEL: INFO
  LOG_FORMAT: json
  TRANSPORT_TYPE: all
  FEDERATION_ENABLED: true
  FEDERATION_DISCOVERY: false
  FEDERATION_PEERS: '[]'
```

---

### 🔗 MCP Standards Check

* [x] Change adheres to current [MCP specifications](https://developer.ibm.com/tutorials/awb-handle-remote-tool-calling-model-context-protocol/)
* [x] No breaking changes to existing MCP-compliant integrations

---

### 🔄 Alternatives Considered

* Manual Kubernetes manifests per environment
* Kustomize overlays (less portable)
* Docker Compose or Podman-only workflows (non-K8s)

---

### 📓 Additional Context

* Consider publishing the chart via GitHub Pages or ArtifactHub
* Consider testing on multiple Kubernetes distributions, including OpenShift
* Helm chart should support ConfigMap-based or secret-based env injection
* Long-term: support multiple replicas, PodDisruptionBudgets, and autoscaling via HPA
* Ensure you document how to use the helm chart in docs, for Kubernetes / OpenShift and Minikube.

This will also make MCP Gateway compatible with Argo CD, Flux, and GitOps flows out of the box.
